# Usa la imagen base de OpenJDK 17
FROM openjdk:17

# Establece el directorio de trabajo en /app
WORKDIR /target

# Copia el archivo JAR construido en el directorio /app
COPY target/user.jar user.jar

# Expone el puerto 8080 para que la aplicación sea accesible
EXPOSE 18082

# Comando para ejecutar la aplicación cuando el contenedor se inicie
CMD ["java", "-jar", "user.jar"]
