# Usa la imagen base de OpenJDK 17
FROM openjdk:17

# Establece el directorio de trabajo en /app
WORKDIR /target

# Copia el archivo JAR construido en el directorio /app
COPY target/notification.jar notification.jar

# Expone el puerto para que la aplicación sea accesible
EXPOSE 18083

# Comando para ejecutar la aplicación cuando el contenedor se inicie
CMD ["java", "-jar", "notification.jar"]
